import { execFileSync } from 'node:child_process'
import { readFileSync, statSync } from 'node:fs'

import { findPii } from '../../src/core/personal-data'

interface Finding {
  readonly file: string
  readonly line: number
  readonly kind: string
  readonly detail: string
}

const SECRET_PATTERNS: readonly { kind: string; pattern: RegExp }[] = [
  { kind: 'private-key', pattern: /-----BEGIN [A-Z ]*PRIVATE KEY-----/ },
  { kind: 'anthropic-key', pattern: /\bsk-ant-[A-Za-z0-9_-]{20,}/ },
  { kind: 'openai-key', pattern: /\bsk-[A-Za-z0-9]{32,}/ },
  { kind: 'aws-access-key', pattern: /\bAKIA[0-9A-Z]{16}\b/ },
  { kind: 'gateway-live-key', pattern: /\b[a-z]{3}_live_[A-Za-z0-9]{10,}/ },
  { kind: 'github-token', pattern: /\bgh[pousr]_[A-Za-z0-9]{30,}/ },
  { kind: 'slack-token', pattern: /\bxox[abprs]-[A-Za-z0-9-]{10,}/ },
  { kind: 'jwt', pattern: /\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/ },
]

const BINARY_EXTENSIONS = /\.(png|jpe?g|gif|pdf|zip|ico|woff2?|ttf|db|sqlite3?)$/i

const PII_EXEMPT = [/^tests\//, /^fixtures\//, /^drizzle\//, /^package-lock\.json$/]

function committableFiles(): string[] {
  const output = execFileSync(
    'git',
    ['ls-files', '-z', '--cached', '--others', '--exclude-standard'],
    { encoding: 'utf8' },
  )
  return output.split('\0').filter((path) => path.length > 0)
}

function shouldScan(path: string): boolean {
  if (BINARY_EXTENSIONS.test(path)) return false
  try {
    return statSync(path).size <= 2_000_000
  } catch {
    return false
  }
}

const findings: Finding[] = []
let scanned = 0

for (const file of committableFiles()) {
  if (!shouldScan(file)) continue
  scanned++

  const contents = readFileSync(file, 'utf8')
  const lines = contents.split('\n')
  const piiExempt = PII_EXEMPT.some((pattern) => pattern.test(file))

  for (const [index, line] of lines.entries()) {
    for (const { kind, pattern } of SECRET_PATTERNS) {
      if (pattern.test(line)) {
        findings.push({ file, line: index + 1, kind, detail: 'possible credential in source' })
      }
    }

    if (piiExempt) continue

    for (const hit of findPii(line)) {
      findings.push({
        file,
        line: index + 1,
        kind: `pii:${hit.kind}`,
        detail: 'personal data must not enter the repository',
      })
    }
  }
}

if (findings.length === 0) {
  console.log(
    `check:secrets: ${scanned} committable files scanned, nothing found ` +
      `(tests/, fixtures/, drizzle/ and the lockfile are exempt from the personal-data scan:\n` +
      ` synthetic or machine-generated by construction. Credential patterns still apply everywhere.)`,
  )
  process.exit(0)
}

console.error(`check:secrets: ${findings.length} finding(s):\n`)
for (const finding of findings) {
  console.error(`  ${finding.file}:${finding.line}  ${finding.kind}  ${finding.detail}`)
}
console.error(
  '\nIf a finding is a deliberate synthetic fixture, move it under tests/ or fixtures/.\n' +
    'Never silence this by weakening the pattern.',
)
process.exit(1)
